name: ATAC-Seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bash=5.0.018
  - bash_kernel=0.7.2
  - bedtools=2.30.0
  - bleach=4.1.0
  - bowtie2=2.4.4
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - cctools_osx-64=973.0.1
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - clang=12.0.1
  - clang-12=12.0.1
  - clang_osx-64=12.0.1
  - clangxx=12.0.1
  - clangxx_osx-64=12.0.1
  - click=8.0.1
  - colorama=0.4.4
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - commonmark=0.9.1
  - compiler-rt=12.0.1
  - compiler-rt_osx-64=12.0.1
  - coreutils=8.31
  - cryptography=3.4.7
  - curl=7.78.0
  - cycler=0.10.0
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=9.3.0
  - gfortran_osx-64=9.3.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=2.9.0
  - htslib=1.13
  - humanfriendly=9.2
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.8.1
  - ipykernel=6.3.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - isl=0.22.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.0.2
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld64_osx-64=609
  - ldid=2.1.2
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp12=12.0.1
  - libcurl=7.78.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm12=12.0.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - llvm-tools=12.0.1
  - lz4-c=1.9.3
  - lzstring=1.0.4
  - macs2=2.2.7.1
  - make=4.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.1.0
  - multiqc=1.11
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.2
  - notebook=6.4.3
  - numpy=1.21.2
  - olefile=0.46
  - openjdk=11.0.9.1
  - openssl=1.1.1l
  - packaging=21.0
  - pandoc=2.14.2
  - pandocfilters=1.4.2
  - pango=1.48.9
  - parso=0.8.2
  - pcre=8.45
  - pcre2=10.36
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.4
  - pixman=0.40.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - r-base=4.0.5
  - r-base64enc=0.1_3
  - r-cli=3.0.1
  - r-crayon=1.4.1
  - r-digest=0.6.27
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=0.5.0
  - r-fastmap=1.1.0
  - r-glue=1.4.2
  - r-highr=0.9
  - r-htmltools=0.5.2
  - r-irdisplay=1.0
  - r-irkernel=1.2
  - r-jsonlite=1.7.2
  - r-knitr=1.33
  - r-lifecycle=1.0.0
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mime=0.11
  - r-pbdzmq=0.3_5
  - r-pillar=1.6.2
  - r-repr=1.1.3
  - r-rlang=0.4.11
  - r-rmarkdown=2.10
  - r-stringi=1.7.4
  - r-stringr=1.4.0
  - r-tinytex=0.33
  - r-utf8=1.2.2
  - r-uuid=0.1_4
  - r-vctrs=0.3.8
  - r-xfun=0.25
  - r-yaml=2.2.1
  - readline=8.1
  - requests=2.26.0
  - rich=10.10.0
  - samtools=1.13
  - send2trash=1.8.0
  - setuptools=57.4.0
  - simplejson=3.17.5
  - six=1.16.0
  - spectra=0.0.11
  - sqlite=3.36.0
  - tapi=1100.0.11
  - tbb=2020.2
  - terminado=0.11.1
  - testpath=0.5.0
  - tk=8.6.11
  - tktable=2.10
  - tornado=6.1
  - traitlets=5.1.0
  - trimmomatic=0.39
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
